import { IConversation } from 'helpers/types';

export const conversation1: IConversation[] = [
  {
    speaker: 2,
    eng: '1.1',
    rus: '1.1',
    timeStart: 0.2,
    timeEnd: 1.1,
  },
  {
    speaker: 0,
    eng: 'Which company do you work for?',
    rus: 'В какой компании вы работаете?',
    timeStart: 2.5,
    timeEnd: 5.0,
  },
  {
    speaker: 1,
    eng: 'I work for Asser Abloy.',
    rus: 'Я работаю на Ассера Аблоя.',
    timeStart: 5.0,
    timeEnd: 7.3,
  },
  {
    speaker: 0,
    eng: 'I dont think I know the name.',
    rus: 'Я не думаю, что знаю это название.',
    timeStart: 7.3,
    timeEnd: 9.4,
  },
  {
    speaker: 0,
    eng: 'What does the company do?',
    rus: 'Чем занимается компания?',
    timeStart: 9.4,
    timeEnd: 11.5,
  },
  {
    speaker: 1,
    eng: 'We make locks and security systems.',
    rus: 'Мы производим замки и охранные системы.',
    timeStart: 11.5,
    timeEnd: 14.8,
  },
  {
    speaker: 1,
    eng: 'Im sure you know some of our brands.',
    rus: 'Я уверен, что вы знакомы с некоторыми из наших брендов.',
    timeStart: 14.8,
    timeEnd: 17.6,
  },
  {
    speaker: 1,
    eng: 'Yale locks or Chubb or Vachette, for example.',
    rus: `Например, "Йельские локоны", "Чабб" или "Вашетт".`,
    timeStart: 17.6,
    timeEnd: 22.5,
  },
  {
    speaker: 0,
    eng: 'No, im afraid I dont.',
    rus: 'Нет, боюсь, что нет.',
    timeStart: 22.5,
    timeEnd: 25.1,
  },
  {
    speaker: 0,
    eng: 'Who are your main competitors?',
    rus: 'Кто ваши основные конкуренты?',
    timeStart: 25.1,
    timeEnd: 27.5,
  },
  {
    speaker: 1,
    eng: 'The eastern company.',
    rus: 'Восточная компания.',
    timeStart: 27.5,
    timeEnd: 29.6,
  },
  {
    speaker: 1,
    eng: 'Ingersoll, Rand, Masterlock.',
    rus: 'Ингерсолл, Рэнд, Мастерлок.',
    timeStart: 29.6,
    timeEnd: 32.8,
  },
  {
    speaker: 0,
    eng: 'Well, I think you can see now that',
    rus: 'Что ж, я думаю, теперь вы понимаете, что',
    timeStart: 32.8,
    timeEnd: 35.3,
  },
  {
    speaker: 0,
    eng: 'I know nothing about the security business.',
    rus: 'Я ничего не смыслю в охранном бизнесе.',
    timeStart: 35.3,
    timeEnd: 37.8,
  },
  {
    speaker: 0,
    eng: 'Wheres the company based?',
    rus: 'Где базируется компания?',
    timeStart: 38.4,
    timeEnd: 40.3,
  },
  {
    speaker: 1,
    eng: 'Its a swedish group.',
    rus: 'Это шведская группа.',
    timeStart: 40.3,
    timeEnd: 42.0,
  },
  {
    speaker: 0,
    eng: 'Oh, okay.',
    rus: 'О, ладно.',
    timeStart: 42.0,
    timeEnd: 43.8,
  },
  {
    speaker: 0,
    eng: 'Is it a very big group?',
    rus: 'Это очень большая группа?',
    timeStart: 43.8,
    timeEnd: 45.7,
  },
  {
    speaker: 1,
    eng: 'Yes, it is.',
    rus: 'Да, это так.',
    timeStart: 45.7,
    timeEnd: 47.3,
  },
  {
    speaker: 1,
    eng: 'We have about 43,000 employees.',
    rus: 'У нас около 43 000 сотрудников.',
    timeStart: 47.3,
    timeEnd: 50.7,
  },
  {
    speaker: 0,
    eng: 'That is big.',
    rus: 'Это очень много.',
    timeStart: 50.7,
    timeEnd: 52.1,
  },
  {
    speaker: 1,
    eng: 'And we have annual sales of more than €5 billion.',
    rus: 'И наш годовой объем продаж составляет более 5 миллиардов евро.',
    timeStart: 52.1,
    timeEnd: 56.7,
  },
  {
    speaker: 0,
    eng: 'So are you mainly in the european market?',
    rus: 'Итак, работаете ли вы в основном на европейском рынке?',
    timeStart: 56.7,
    timeEnd: 59.9,
  },
  {
    speaker: 1,
    eng: 'No, we operate in over',
    rus: 'Нет, мы работаем в более чем',
    timeStart: 59.9,
    timeEnd: 62.1,
  },
  {
    speaker: 1,
    eng: '70 different countries worldwide.',
    rus: '70 различных стран по всему миру.',
    timeStart: 62.1,
    timeEnd: 65.2,
  },
  {
    speaker: 1,
    eng: 'There are 150 different companies in the group.',
    rus: 'В группу входят 150 различных компаний.',
    timeStart: 65.2,
    timeEnd: 69.4,
  },
  {
    speaker: 0,
    eng: 'And which part of the company do you work for?',
    rus: 'И в каком подразделении компании вы работаете?',
    timeStart: 69.4,
    timeEnd: 72.7,
  },
  {
    speaker: 1,
    eng: 'Besam.',
    rus: 'Бесам.',
    timeStart: 72.7,
    timeEnd: 73.7,
  },
  {
    speaker: 1,
    eng: 'B E S a m.',
    rus: 'Б Е С а м.',
    timeStart: 74.3,
    timeEnd: 78.2,
  },
  {
    speaker: 1,
    eng: "It's a subsidiary of the main company.",
    rus: 'Это дочерняя компания основной компании.',
    timeStart: 78.2,
    timeEnd: 81.0,
  },
  {
    speaker: 1,
    eng: 'We specialise in automatic door mechanisms.',
    rus: 'Мы специализируемся на автоматических дверных механизмах.',
    timeStart: 81.6,
    timeEnd: 85.5,
  },
  {
    speaker: 1,
    eng: 'Who do you work for?',
    rus: 'На кого вы работаете?',
    timeStart: 85.5,
    timeEnd: 87.3,
  },
  {
    speaker: 0,
    eng: 'Microsoft.',
    rus: 'Майкрософт.',
    timeStart: 87.3,
    timeEnd: 88.7,
  },
  {
    speaker: 1,
    eng: 'And what does your company do?',
    rus: 'А чем занимается ваша компания?',
    timeStart: 88.7,
    timeEnd: 91.5,
  },
  {
    speaker: 0,
    eng: 'We make...',
    rus: 'Мы создаем...',
    timeStart: 91.5,
    timeEnd: 92.5,
  },
  {
    speaker: 0,
    eng: "That's a joke, right?",
    rus: 'Это ведь шутка, да?',
    timeStart: 93.8,
    timeEnd: 94.9,
  },
];
